library(actverse)
library(checkmate)
library(testthat)

test_check("actverse")

# # For development use only (comment the code after use (Ctrl + Shift + C))
#
# .rs.restartR()
# BiocCheck::BiocCheck()
# codemetar::give_opinions()
# codemetar::write_codemeta()
# covr::package_coverage()
# devtools::check()
# devtools::document()
# devtools::install()
# devtools:test()
# goodpractice::gp()
# normalizePath(readClipboard(), "/", mustWork = FALSE)
# pkgdown::build_article("")
# pkgdown::build_favicons(overwrite = TRUE)
# pkgdown::build_reference(preview = FALSE)
# pkgdown::build_site(preview = TRUE)
# rhub::check_for_cran()
# spelling::spell_check_package()
# spelling::update_wordlist()
# urlchecker::url_check()
# usethis::use_coverage()
# usethis::use_github_action("check-pak")
# usethis::use_github_action("pkgdown-pak")
# usethis::use_github_action("test-coverage-pak")
# usethis::use_logo("./.archive/ai/hex-logo.png")
# usethis::use_pkgdown_github_pages()
# usethis::use_tidy_description()
